services:
  backend_node:
    container_name: backend_node
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "82:3000"
    # El restart lo que hace es -unless-stopped-Reiniciar siempre, excepto si tú mismo lo detuviste manualmente
    # El restart lo que hace es -always-reiniciar el contenedor, pase lo que pase a veces no necesitamos que este reiniciando 
    restart: unless-stopped
    depends_on:
      - base_datos_mysql

  base_datos_mysql:
    container_name: base_datos_mysql
    image: mysql:9.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_base_defecto
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_service:/var/lib/mysql

  db_phpmyadmin:
    container_name: db_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: base_datos_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7777:80"
    depends_on:
      - base_datos_mysql

volumes:
  mysql_data_service: